### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [tward3/prj-rev-bwfs-dasmoto#5]
**Summary Grade: Satisfactory**

Good job! Your files are organized nicely, and you did a great job of following the client specification -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed excellent code practice, so make sure to keep that up!

I have made some comments in your code to take note of. First off, great job making use of id's and classes appropriately -- many learners seem to confuse this concept, so great job getting that right. One area of improvement is you should make sure to comment the main parts of your code in future projects. This greatly helps your development flow, especially as your projects get larger and more complex since they serve as a reminder to why you decided to code something a particular way. Here is a quick refresher on commenting in HTML and CSS, respectively:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/31051903-f771621c-a642-11e7-96ee-aafdd05d6fe7.png">

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/31051905-f8754a2a-a642-11e7-83c7-be4da560a101.png">

Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs).

**Comment by tward3** [comment]
Thanks for your detailed feedback.  I agree that using id's and classes can be tricky.  I'm still trying to make sure I have the concept fully integrated into by brain!  I think I have it as evidenced by this project.

You mentioned that you made some comments in my code - I don't see them.  I've never used GitHub before, but I assume all I need to do is open the code files where they are stored in GitHub and I should see your comments there.  I note my code shows "1 contributor."  I would expect to see "2 contributors" if your comments had been saved.  Thanks for clarifying where to see your comments.

What are the various Summary Grades given out?  Is "Satisfactory" the best?  It appears that you believe I did a "Great job overall!" so I'm just curious.  It appears the only thing I "missed" was commenting my code.  Two points on this: 1. I don't feel the course work so far has really emphasized commenting.  It has only shown us how to do it in HTML code.  2. I don't believe we were instructed how to comment within CSS code - specifically, I don't recall ever seeing the: /* This is a comment */ syntax in the lessons so far.  I recall only seeing the HTML comment syntax <-- This is a comment -->  So thanks for mentioning the importance of commenting; I will comment more in the future.

As you suggest, I will play around with more styling for fun.

Thanks!

**Comment by ad3429** [comment]
No problem! Usually 'satisfactory' is given out if you have completed the assignment fully and met all expectations, but we do very rarely give a grade above that in the case that you went above and beyond by implementing an additional cool feature/had great styling. These are very rare cases though, and so satisfactory really means excellent job!
